### ISSUE TITLE
ImportError:yahoo_equities

### ISSUE THREAD

**Issue by vibeinging** [rainx/zipline_cn_databundle#6]
您好，出现ImportError，想问一下 如何切换成tushare的呢？
Traceback (most recent call last):
  File "/Users/XXX/Quant/zipline_test_python3/test.py", line 3, in <module>
    from zipline_cn_databundle.squant_source import squant_bundle
  File "/Users/XXX/Quant/zipline_test_python3/venv/lib/python3.6/site-packages/zipline_cn_databundle/__init__.py", line 1, in <module>
    from .yahoo import (
  File "/Users/XXX/Quant/zipline_test_python3/venv/lib/python3.6/site-packages/zipline_cn_databundle/yahoo.py", line 1, in <module>
    from zipline.data.bundles import register, yahoo_equities
ImportError: cannot import name 'yahoo_equities'

**Comment by rainx** [comment]
这个代码有一阵子没维护过了，可以试试修改一下 squant_source 实现，yahoo的应该已经无法提供服务了，tushare的也不太确定

**Comment by vibeinging** [comment]
好的 谢谢

**Comment by rubiiisweetheart** [comment]
> 好的 谢谢
我有同样的问题…请问最后怎么解决的呢？hmmm我不会改squant_source…谢谢🙏
